# Generated by Django 6.0.6 on 2026-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('education_level', models.CharField(max_length=150)),
                ('skills', models.TextField()),
                ('work_experience', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('github_profile', models.URLField(blank=True)),
                ('portfolio_website', models.URLField(blank=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='passport_photos/')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='generated_resumes/')),
            ],
        ),
    ]
